### ISSUE TITLE
'=' does not work on duration

### ISSUE THREAD

**Issue by meinnamehier** [fnep/mtv_dl#1]
a search like 
`mtv_dl list topic="Die Sendung mit der Maus" duration=30m`
does not produce any results, even though it is stated that it should work:

>   '='  Pattern is a regular expression case insensitive search within the field value.
>         Available for the fields 'description', 'start', 'duration', 'age', 'region',
>         'size', 'channel', 'topic', 'title', 'hash' and 'url'.

Searching without duration shows that there should be search results.

Btw, great work! I am very excited about having found this!

**Comment by fnep** [comment]
Wow, thank you for finding this. :)

I guess I never noticed because I'm always using e.g. `duration+25m` in those cases to find all shows longer than the defined time.

The package is updated on pypi and should work now.
