### ISSUE TITLE
Geoblocking: Mediathek von SRF

### ISSUE THREAD

**Issue by schui95** [fnep/mtv_dl#10]
Guten Abend

Vielen Dank für das einfache und schlanke Tool!
Ich habe Probleme neuere Sendungen vom SRF zu finden und dann herunterzuladen.
Beispiele wären:

```
channel=SRF topic=#SRFglobal duration+20m
channel=SRF topic=Deville duration+20m
channel=SRF topic=Einstein duration+45m
```

Kann es sein, dass Geoblocking oder so aktiviert ist und somit nicht die vollständige Datenbank heruntergeladen wird oder verwende ich das Tool einfach falsch. Für Sendungen im ZDF oder ARD funktioniert es bisher einwandfrei.
Vielen Dank für jede Hilfe.

Gruss schui95

**Comment by fnep** [comment]
Hallo,

das Problem ist hier, dass die Shows vom SRF irgendwie keine Größenangabe haben und das Script solche scheinbar falschen Einträge ignoriert. Wenn man das im code einfach übergeht, zeigt sich, dass der SRF die Videos als m3u8 Liste aber eben nicht im HLS Format liefert, was so in der aktuellen Version nicht unterstützt ist.

Ich habe mal eine experimentelle Implementierung gepusht, die in der das geht und würde mich freuen, wenn du sie testet. Ich arbeite eh gerade an einer neuen Version in der die Datenbank als sqlite abgelegt wird und freue mich auch hier wenn das mal jemand anderes testet.

Kannst du hier von Github mal den Branch "next" auschecken und prüfen, ob es damit geht?

**Comment by schui95** [comment]
Alles klar. Mir ist aufgefallen, dass das SRF jeweils einen Downloadlink zu einer vollständigen MP4-Videodatei auf der jeweiligen Webseite zur Verfügung stellt. Ist es dokumentiert wie Mediathekview die Informationen für die Einträge für die Sendungen holt? Vielleicht kann man es so etwas optimieren oder anpassen.

Danke! Die experimentelle Implementierung (Branch "next") funktioniert soweit so gut. Wie du beschrieben hast, fehlt die Grössenangabe in der Auflistung der Sendungen. Die heruntergeladenen Sendungen sind jeweils im ".ts" Format und nicht im gewöhnlichen ".mp4".

**Comment by fnep** [comment]
Leider weiß ich auch nicht wie genau der Parser an diese Informationen kommt, generell müsste man sowas im dortigen Repo anregen. Die Endung .ts wird so aus der .m3u8 Datei übernommen. Ich könnte das zwar blind ändern, aber ich weiß ja nicht wirklich welches Format/Container die Datei hat.

Super jedenfalls wenn es für dich klappt. Ich plane noch ein paar weitere Änderungen vor dem Release aber lange kann es nicht mehr dauern.

**Comment by schui95** [comment]
Mir ist noch etwas anderes aufgefallen aber möchte deswegen kein neues Ticket eröffnen: 
Beim Verwenden des Parameters --dir='Folder' erscheint eine unklare Fehlermeldung falls der 'Folder' nicht existiert. 

python3 mtv_dl.py download --dir=./test --high --target='{dir}/{channel}/[{topic} {date}] {title}{ext}' --sets=shows.txt

`2020-05-14T15:38:28+0200 CRITICAL <class 'requests.exceptions.ConnectionError'>: HTTPConnectionPool(host='verteiler5.mediathekview.de', port=80): Max retries exceeded with url: /Filmliste-akt.xz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f846f25c100>: Failed to establish a new connection: [Errno 111] Connection refused'))
  File "mtv_dl.py", line 1148, in <module>
    main()
  File "mtv_dl.py", line 1092, in main
    showlist = Database(filmliste=cw_dir / FILMLISTE_DATABASE_FILE,
  File "mtv_dl.py", line 410, in __init__
    self.initialize_filmliste()
  File "mtv_dl.py", line 344, in initialize_filmliste
    cursor.executemany("""
  File "mtv_dl.py", line 490, in _get_shows
    with self._showlist() as showlist_path:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "mtv_dl.py", line 453, in _showlist
    response = requests.get(url, stream=True)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
`

Das Programm beendet sich dann natürlich, doch der ausgewählte Ordner existiert nun. Mit mehreren neuen Neustarts lässt sich aber das Programm nicht mehr richtig verwenden.
Mit einem Workaround lässt sich das Problem beheben: Den Ordner manuell löschen und mit 'mkdir test' wieder erstellen. Dann funktioniert das Programm mit dem obigen Befehl. Ich weiss leider momentan nicht an was es liegen könnte. 

PS: Es wäre schön, wenn die Fehlermeldung aussagekräftiger wäre.

**Comment by fnep** [comment]
Ich denke, das ist ein Irrtum. Das hat nichts mit dem `--dir='Folder'` zu tun, sondern damit das aus unklaren Gründen die Filmliste nicht geladen werden konnte (der Server nicht erreichbar bar). Blöd, dass er dann in so einem halbfertigen Zustand stecken bleibt. Beim nächsten mal sollte erkannt werden, dass die Filmliste fehlt.

Ich schau mir das dieser Tage mal an. 👍

**Comment by schui95** [comment]
Okay, super. Falls du noch mehr Details oder so brauchst einfach bescheid sagen. Ich werde in den nächsten Tagen auch noch experimentieren.

**Comment by fnep** [comment]
Ich denke, ich konnte es beheben. War am Ende recht banal. 

Probier bitte nochmal.

**Comment by schui95** [comment]
Das Problem scheint nun behoben zu sein! Danke :)
