### ISSUE TITLE
Switch to SQLite, will it migrate

### ISSUE THREAD

**Issue by bjoerns1983** [fnep/mtv_dl#13]
Hi there,
ive just seen that some months ago you switch to sqlite for the history db.
Before  i update (i think i use the version from end of last year) i would like to know if my old history will be migrated?
Else i would have to edit my shows.txt to only download new shows after the current date.

**Comment by fnep** [comment]
I'm sorry to say that but it will not.

I was about to integrate code to do so, but at this point I also decided to use a built-in hash algorithm to reduce dependencies further. So migration became impossible.
