### ISSUE TITLE
Most Filmliste URLs down?

### ISSUE THREAD

**Issue by bjoerns1983** [fnep/mtv_dl#15]
Hi there,
i have just stumbled upon the problem that my mtv_dl install stopped downloading since the 11. June.
After digging a bit around i found auf that several of the URL in FILMLISTE_URLS seem to be down (verteiler2 to verteiler6). I tried it with my homeconnection and a VPS on both i get an unknown host message when i try to ping  them.

**Comment by fnep** [comment]
You are right, I noticed something similar a few weeks ago for a single server and then it came back. 

Anyhow, i will cleanup the list in the next days. There is a xml file with the list of all servers (https://res.mediathekview.de/akt.xml) and earlier it really had a list in it. These days there is only the single url (`liste.`) so they are probably simply migrating away from this. 

Thank you for opening this ticket so i keep track. :)

**Comment by bjoerns1983** [comment]
No problem, for now i will simply edit my local mtv_dl.py and remove the not working URL's. The last one from onlinetvrecorder seems to work although i dont know if the data which is returned is up-to-date if it is missing in the server list.

**Comment by bjoerns1983** [comment]
Official Announcement regarding the URL's: https://forum.mediathekview.de/topic/3508/aktuelle-verteiler-und-filmlisten-server

**Comment by fnep** [comment]
This should be fixed in v0.14 now.
