### ISSUE TITLE
Nothing happens until i hit Ctrl+C

### ISSUE THREAD

**Issue by meinnamehier** [fnep/mtv_dl#2]
Hello again,

I have a weird issue with two separate computers:
1) Raspberry Pi 3B+ running Python 3.7.1
2) Macbook Pro with Ubuntu Budgie running Python 3.6.7

When I start a command like 
`mtv_dl list topic="Lenas Ranch" `
nothing happens until i hit ctrl+C and then it starts executing.
see here pasted from my terminal:

> mtv_dl download -v topic="Lenas Ranch"
> ^C2019-01-31T22:05:18+0100 DEBUG    Opening database from 'http://verteiler2.mediathekview.de/Filmliste-akt.xz'.

Now I assume I am missing something very obvious, but I don't know what it is.

**Comment by meinnamehier** [comment]
[logfile.log](https://github.com/efenka/mtv_dl/files/2819062/logfile.log)
Here is the output from strace, don't know if it helps

**Comment by fnep** [comment]
Thank you for this detailed bug report :)

I guess that for some reason the file locking is not working. mtv_dl is trying to lock the file `.Filmliste-akt.xz.cache` for reading and writing. 

Just to confirm: Could you please wait more than 60 seconds until pressing CTRL-C? There is a built in timeout. After this time, you should get an exception with a traceback. This output would help to figure out how to work around.

The strace is very helpful in this case, the interesting part is here:

    29658 openat(AT_FDCWD, "/media/ds_video/incoming/.Filmliste-akt.xz.cache", O_RDONLY|O_CLOEXEC) = 3
    29658 ioctl(3, FIOCLEX)                 = 0
    29658 fstat(3, {st_mode=S_IFREG|0777, st_size=210153508, ...}) = 0
    29658 ioctl(3, TCGETS, 0x7fff105fb220)  = -1 ENOTTY (Inappropriate ioctl for device)
    29658 brk(0x1e28000)                    = 0x1e28000
    29658 lseek(3, 0, SEEK_CUR)             = 0
    29658 flock(3, LOCK_EX|LOCK_NB)         = -1 EBADF (Bad file descriptor)

May it be that /media/ds_video/incoming/ is some mounted NFS/SMB/WebDAV or so? Is it a "normal" local file system or something special?

**Comment by meinnamehier** [comment]
The directory is mounted via NFS, coming from a Synology NAS, formatted as ext4.
I will do some tests tonight.

**Comment by fnep** [comment]
Ok. Locking on NFS is not so easy. 

If this turns out to be the issue, you may try to give the option 

    --dir /some/local/directory/to/work/in/

together with the option 

    --target "/media/ds_video/incoming/{{channel}}/{{topic}}/{{start}} {{title}}{{ext}}"

to seperate the database cache form you actual files. The later option is only relevant for downloads.

**Comment by meinnamehier** [comment]
It works! Great, thanks for the help. I will close this issue.
(Maybe you want to add a hint about this in the documentation)

Thanks a lot for the script and your effort, i will definitely use this :)
