### ISSUE TITLE
Sorting of list

### ISSUE THREAD

**Issue by imolb** [fnep/mtv_dl#25]
Is the list shown with command "list" anyhow sorted?

Proposal 1 (sufficient for me): Have a default sorting by age.
Proposal 2 (more general): Add an additional command line parameter to define the column to sort by.

-----
And by the way: Many thanks for this cool script and even more for the extremely fast reactions.

**Comment by fnep** [comment]
Good objection, the sorting comes from the Filmliste source files, but it is not really sorted. I will add a sorting for start time (what is more or less the same as age) and consider extending this in a later version.
