### ISSUE TITLE
Moving file to user target: Invalid cross device link

### ISSUE THREAD

**Issue by meinnamehier** [fnep/mtv_dl#3]
Hello once again,
I now have the problem that the file is not moved to the new location on the mounted NFS drive with 
> [Errno 18] Invalid cross-device link
This seems to be due to the usage of Path.rename in _move_to_user_target (line 719) which apparently does not work across different filesystems.
Is it possible to use some other method for moving the file (like shutil.move) in case Path.rename fails?
Being a non-software developer, I can only guess what needs to be done and my solution would not be as robust as anything you could come up with.
Thanks for making this great tool, I really hope I can use it for my use cases :)

**Comment by fnep** [comment]
Thank you for reporting this. I'm happy to find all the bugs. I developed the script primarily for my own and so my test-user-base is pretty small and covers not all cases.

I just tested it and will switch to `shutil.move` and publish a new version.

**Comment by fnep** [comment]
Ok, please try again with version 0.8 🤞.

**Comment by meinnamehier** [comment]
It worked! Thanks a lot, this script really great to have!
