### ISSUE TITLE
Add extension automatically to the --target

### ISSUE THREAD

**Issue by imolb** [fnep/mtv_dl#30]
The file extension {ext} should automatically be added to the --target.

If the user specifies "--target=test.mp4" the movie will be downloaded and then overwritten with the subtitles and then overwritten with the nfo-file, because all three files write to test.mp4 (see log below).
So the user _has_ to specify {ext} in the target, otherwise the output will be useless. But if the user has to specify it, why not add it automatically?

Just adding {ext} to each --target will be not backwards compatible to older configurations.

Proposal 1: Automatically add {ext} to --target in the script, if {ext} is not existing in --target.
Proposal 2: Give a warning if {ext} is not in --target and subtitles or nfo are generated.

```
python3 mtv_dl.py download -o --target=test.mp4 hash=2f2bad3ed7c                                        
2020-07-16T14:52:08  INFO     Saved show 'Der erste April (26)' (ARD, 'Meister Eder und sein Pumuckl', 2020-07-05 04:40:00, 2f2bad3ed7c) to PosixPath('test.mp4').                                
2020-07-16T14:52:09  INFO     Saved subtitles 'Der erste April (26)' (ARD, 'Meister Eder und sein Pumuckl', 2020-07-05 04:40:00, 2f2bad3ed7c) to PosixPath('test.mp4').                           
                     INFO     Saved nfo 'Der erste April (26)' (ARD, 'Meister Eder und sein Pumuckl', 2020-07-05 04:40:00, 2f2bad3ed7c) to PosixPath('test.mp4').
```

**Comment by fnep** [comment]
Good point, probably this also not clear enough from the --help menu.
