### ISSUE TITLE
Set file date to aired date

### ISSUE THREAD

**Issue by imolb** [fnep/mtv_dl#31]
The download runs smooth and the downloads are shown with pretty title and plot in Kodi with the .nfo file! Very cool!

Unfortunately the skins in Kodi don't use the <aired> parameter in the .nfo file but instead the file modification time to show and sort the files by date.
Therefore following improvement: Have an additional parameter --set-file-mod-time. If this parameter is set, after downloading the file modification time is set to the aired time.

See PR #32 below.

**Comment by fnep** [comment]
Pretty cool, thank you for the patch.
