### ISSUE TITLE
sqlite3.OperationalError on Alpine Linux

### ISSUE THREAD

**Issue by meinnamehier** [fnep/mtv_dl#35]
Hi!
I just installed mtv_dl on an Alpine Linux VM.
I was able to do a couple of list commands, and then all of a sudden, this error message popped up:
```
2020-11-05T10:34:15  CRITICAL <class 'sqlite3.OperationalError'>: unable to open database file

                                File "/home/matti/.local/bin/mtv_dl", line 8, in <module>

                                  sys.exit(main())
                                File "/home/matti/.local/lib/python3.8/site-packages/mtv_dl.py", line 1202, in main
                                  showlist = Database(filmliste=cw_dir / FILMLISTE_DATABASE_FILE,
                                File "/home/matti/.local/lib/python3.8/site-packages/mtv_dl.py", line 414, in __init__
                                  self.connection = sqlite3.connect(filmliste_path.absolute().as_posix(),
```

Rebooting didn't change anything, also there is enough space on the drive.

**Comment by fnep** [comment]
Ugh, hard to tell what the exact reason for this is, but in general I would say the tool is unable to access the Filmliste database file. 

The database file is located at "{current working directory}/.Filmliste.{script_version}.sqlite". This can be caused by permission issues but probably also by a corrupted file. I would recommend deleting the file. The mtv_dl tool will detect that it's missing and generate a new one. The Filmliste sqlite file is there for caching purposes only.

Did this help?

**Comment by meinnamehier** [comment]
Well, it worked once: I deleted the Filmliste file, rebooted and it worked.
After another reboot, the Filmliste file was gone (thatsweird) and i get the same error message. (Thats weird, because it should be recreated as you said above).
I have a feeling there is something wrong with my VM image.

**Comment by fnep** [comment]
Probably, yes. Maybe it helps to put the working directory to some different place with `--dir=PATH`. 

If I can help you to make it work from the mtv_dl side, please let me know - but it feels like it's coming from the system side.

**Comment by meinnamehier** [comment]
I think i found something: The problem occurs after I create a .mtv_dl.yml file in my home directory with this content:
```
high: true
dir: /media/downloads
target: '{dir}/[{topic} {date}] {title}{ext}'
```
If i delete the file, it works again.
This happened on a Debian VM and my MacOS.
Should I open another bug ticket for this?
Also interesting: the folder /media/downloads was the mount target for a cifs (smb) mount. Changing this to an unmounted directory makes it work again

**Comment by meinnamehier** [comment]
yeah, well, i feel stupid now. i didn't realize that "dir" is where the database file is stored. so if i change that in the config file, the script will be looking there. sorry to have bothered you. ;)

**Comment by fnep** [comment]
No problem. Glad that it works now.
