### ISSUE TITLE
Feature proposal: trigger script after successful download

### ISSUE THREAD

**Issue by ChristianKuehnel** [fnep/mtv_dl#36]
Thx for building this great tool 👍  ! It fits my use case much better than the Mediathek!

After downloading a video, I would like `mtv_dl` to trigger a local script. In my case I want the script to do 2 things: Send me an email about the new download and trigger Jellyfin to update the media library.

The script should be called with configurable arguments, similar to the path configuration, in the config file:
```yaml
post-download: /some/path/myscript "{title}" "{path}"
```

Design proposal, in case you would like me to implement this:
* Somewhere after the [download](https://github.com/efenka/mtv_dl/blob/124a13e23f23092dadc9a186d99177665fcabe37/mtv_dl.py#L1246), if the `post-download` option is set:
  * `subprocess.call` the script with `shell=True`
  * If successful: print that script was called successfully, hide the script output.
  * On failure: print the script output to the console and continue. `mtv_dl` should continue it's work even if the post-download script fails.

What do you think?

**Comment by fnep** [comment]
I like the Idea. 👍 

I'm honestly not so sure if the transmission of details about the download via command line arguments is the right choice - I personally would give the details as environment arguments instead. Would this also work for you?

**Comment by ChristianKuehnel** [comment]
I like the idea with environment variables. 

This would allow us to hand over e.g. everything that is contained in a `mtv_dl dump` and let the user to pick the ones they need. Maybe name the variable `mtv_dl_<attribute>` (or something similar) so avoid name clashes.

**Comment by fnep** [comment]
Perfect. Good idea with the naming scheme. I've put it in my list and will see if I can realize it next week.

**Comment by fnep** [comment]
In master branch, there is now a new post-download option. Please have a look if it works as expected, so I can release it with the next version.

**Comment by ChristianKuehnel** [comment]
Thx for implementing this! It works nicely.

One small request: could you add [os.path.expanduser()](https://docs.python.org/3/library/os.path.html#os.path.expanduser) to the function? Then I could use `~/bin/myscript.sh` as argument instead of making at an absolute path.

FYI: sending telegram from the shell is quite easy: https://github.com/fabianonline/telegram.sh

**Comment by fnep** [comment]
Sure, please have another look.

**Comment by ChristianKuehnel** [comment]
Hi @efenka , I can confirm that hooks with `~`  in their paths are now also working.
Thank you for all the effort you've put into this great tool!

**Comment by fnep** [comment]
Perfect. Just released v0.17 minutes ago.
