### ISSUE TITLE
Publishing mtv_dl to Docker Hub

### ISSUE THREAD

**Issue by lucanello** [fnep/mtv_dl#37]
You already added the possibility to run mtv_dl inside a Docker container. What is missing in my opinion is the published image on Docker Hub for even easier use. Right now, you have to clone the repository in order to build the image. I would prefer to simply pull the image off the Docker Hub repository and begin to use it.

I would suggest using an automatic build pipeline which can be connected to this Git repository. You can define that the "latest" image and an image containing the version tags is built whenever a new release is published. Additionally I would suggest building a "dev" image on each commit to the main-branch. This way newest features are available asap.

**Comment by fnep** [comment]
It's already there. I added it #9, but never received a positive feedback from the asking user back then, so I never added it to the README. Difference is I use the tags for versions but latest for tracking the master branch. Maybe not my smartest decision.

⇾ https://hub.docker.com/r/efenka/mtv_dl

**Comment by lucanello** [comment]
> It's already there. I added it #9, but never received a positive feedback from the asking user back then, so I never added it to the README. Difference is I use the tags for versions but latest for tracking the master branch. Maybe not my smartest decision.
> 
> ⇾ https://hub.docker.com/r/efenka/mtv_dl

Ah perfect, thanks for clarification. You could change the tagging but as long as it's published somehow, it's fine for me.

**Comment by fnep** [comment]
Maybe I have to dive deeper into how docker hub works, but is also was not able to auto-build always the highest tagged version. So would have to create a "latest" tag in git and move this always, what felt a bit "wrong" for me.

**Comment by lucanello** [comment]
> Maybe I have to dive deeper into how docker hub works, but is also was not able to auto-build always the highest tagged version. So would have to create a "latest" tag in git and move this always, what felt a bit "wrong" for me.

I believe you can build on release and simply regex to any git-release tag: https://stackoverflow.com/a/44796846/14814219

```| Type   | Name                              | Dockerfile Location | Docker Tag Name |
|--------|-----------------------------------|---------------------|-----------------|
| Branch | master                            | /                   | latest          |
| Tag    | /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | /                   | {\1}            |
| Tag    | /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | /                   | {\1}.{\2}       |
| Tag    | /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/ | /                   | {\1}.{\2}.{\3}  |

**Comment by fnep** [comment]
Sure, this is what I did, but I cannot pin "latest" to the highest version-tagged commit. I would have to create a "latest" git tag and with every version I publish, would have to remove and add it again to a different commit. See what I mean?

<img width="892" alt="Screenshot 2021-02-01 at 14 51 47" src="https://user-images.githubusercontent.com/2083099/106467623-33678f00-649d-11eb-9099-87f2f2fcb9ad.png">
(this is the perspective from the backend)

**Comment by lucanello** [comment]
> Sure, this is what I did, but I cannot pin "latest" to the highest version-tagged commit. I would have to create a "latest" git tag and with every version I publish, would have to remove and add it again to a different commit. See what I mean?
> 
> <img alt="Screenshot 2021-02-01 at 14 51 47" width="892" src="https://user-images.githubusercontent.com/2083099/106467623-33678f00-649d-11eb-9099-87f2f2fcb9ad.png">
> 
> (this is the perspective from the backend)

Shouldn't this be possible though?
![Bildschirmfoto 2021-02-01 um 21 42 28](https://user-images.githubusercontent.com/1607904/106515764-6d08bc00-64d6-11eb-8832-5c2c0b33fb6c.png)
Having latest as any latest release, dev as any commit to the master/main branch and the version tags from each git-tag?

**Comment by fnep** [comment]
Ok, I will give it a try and changed the config accordingly, even if I'm not sure if the "latest" tag really works as expected. I will see as soon as I publish a new tag.
