### ISSUE TITLE
The exclude-future options hides all shows from today

### ISSUE THREAD

**Issue by imolb** [fnep/mtv_dl#39]
The exclude-future option (respective not setting the --include-future option) hides all show of the current day, so also the shows in the past of the current day.

Steps to reproduce: (assume current time is 21:00):
`mtv_dl.py list age-20h`
will not show a single show.
`mtv_dl.py list --include-future age-20h`
will show a lot of shows in the past of the current day.

Proposal: Consider also the hour of the day, and not just the date, when filtering the shows.
Change
`where.append("date(show.start) < date('now')")`
to
`where.append("datetime(show.start) < datetime('now')")`

**Comment by fnep** [comment]
Nice :), thank you for your work.
