### ISSUE TITLE
feature request: subtitle downloading

### ISSUE THREAD

**Issue by pbienst** [fnep/mtv_dl#4]
There does not seem to be an option to download subtitles, although doing a JSON dump of a certain program hash does reveal a working URL for the subtitles.

**Comment by fnep** [comment]
Interesting idea. Have you tried to apply the subtitles to one of the files? 

I know some tools are able to detect there is a subtitle file next to the media file ans then load it, but i always thought this is not the normal case and one has to "burn" the subtitle in the files.

If this helps, i could try to put the files next to the media files if available.

**Comment by pbienst** [comment]
"Burning" of subtitles in the video file is the atypical case, an external *.srt or *.vrt file is the common case and more flexible. The xml file would need to be converted to one of these formats, but that can be done by calling an external program.

See e.g.
https://github.com/hubwub/xml-to-srt

**Comment by fnep** [comment]
- Have you tried this workflow already (getting the url from the json output, processing it with the mentioned program, play it in a supporting player)?
- Do you have an example hash where subtitles are available?

**Comment by pbienst** [comment]
`mtv_dl download hash=152cd6bf`

The python script I mentioned above does not work, so I've quickly thrown something together that does work. Only tested on that particular program though, but e.g. VLC media player shows it without problems.

```
import re, sys
from bs4 import BeautifulSoup

if len(sys.argv) < 2:
    print("Need file name!")
    sys.exit(2)

s = open(sys.argv[1]).read()

soup = BeautifulSoup(s, "html.parser")

parse_time = lambda time: time.replace(".", ",") #time[:-3] + "," + time[-2:] + "0"

colour_to_rgb = {
    "textBlack": "#000000", 
    "textRed": "#FF0000",
    "textGreen": "#00FF00",
    "textYellow": "#FFFF00",
    "textBlue": "#0000FF",
    "textMagenta": "#FF00FF",
    "textCyan": "#00FFFF",
    "textWhite": "#FFFFFF"}
    
def font_colour(text, colour):
    return "<font color=\"%s\">%s</font>\n" % (colour_to_rgb[colour], text)

srt = ''
for p_tag in soup.findAll("tt:p"):
    # id: sub0 --> 1
    srt += str(int(p_tag.get("xml:id").replace("sub", ""))+1) + "\n"
    srt += "%s --> %s\n" % (parse_time(p_tag.get('begin')), parse_time(p_tag.get('end')))
    for span_tag in p_tag.findAll('tt:span'):
        srt += font_colour(span_tag.text, span_tag.get('style')).replace("&apos", "'")
    srt += '\n\n'
f = open(sys.argv[1][:-4] + ".srt", 'w')
f.write(srt)
f.close()
```

**Comment by fnep** [comment]
Ok, i tried to add it. Please give version .9 a try.

**Comment by pbienst** [comment]
Works perfectly, thanks for the quick turnaround!
