### ISSUE TITLE
hash timezone dependent

### ISSUE THREAD

**Issue by maweki** [fnep/mtv_dl#54]
So I just started moving a few services from different raspberryPis onto a single 10W TDP NUC, to have lower power usage, better peak performance, and a single point of failure. Yeah me.

I plugged the external drive with the library and history file etc. into the new system, ran the usual download script and `mtv_dl` wanted to redownload everything. The hashes differed everywhere, which shouldn't be.

```
  cd6670d4e3c │ ARD      │ Extra 3 vom 25.08.2022 im Ersten                        │ extra 3                                                │ 429  │ 2022-08-25T22:50:00+02:00 │ 44m 3s     │ None │ DE          │ 2022-08-26T01:37:44+02:00  
  90b260f6adc │ ARD      │ Extra 3 vom 25.08.2022 im Ersten                        │ extra 3                                                │ 429  │ 2022-08-25T22:50:00+02:00 │ 44m 3s     │ None │ DE          │ 2022-09-12T16:58:53+02:00  
```

I apparently had different locale and TZ settings. After setting the locale from C to German UTF-8 and the TZ from London to Berlin, and rebooting, (and probably redownloading the mediathek database file) `mtv_dl` had the correct hashes and picked up the history.

I don't know which part (I feel timezone, even though at first glance the code looks agnostic to it and the formatted start times are the same as well), but somehow the hash value is not completely agnostic of some environment settings.

I guess to replicate:
* Check hash `/usr/local/bin/mtv_dl dump title="FIFA und die WM 2022 in Katar"`
* Change locale and TZ, reboot
* Check hash again (database needs to be redownloaded, probably), notice difference

**Comment by fnep** [comment]
>  and a single point of failure

😂 

---

Honestly, I'm not so sure what to do here. From my understanding, the hash generation works without the timezone, but after mtv_dl [uses a "hack" to parse the timestamp](https://github.com/fnep/mtv_dl/blob/7d071c9f3057220a28a7e39708d6072c555fcfb3/mtv_dl.py#L554) to make it work with windows, I'm a bit lost to say if it really works in all cases. I also don't see so many ways to fix it. Replicating the issue in docker did not work for me. :/

**Comment by maweki** [comment]
We can close this alright, as it works for me now and that's all that counts. :smile: 

Okay, so I have a pretty good idea of what's going on here:

```
root@artemis:~# cat /etc/timezone && python3 -c "import datetime; print(datetime.datetime(2020,10,10).timestamp());"
Europe/Berlin
1602280800.0
```

```
root@vidserv:~# cat /etc/timezone && python3 -c "import datetime; print(datetime.datetime(2020,10,10).timestamp());"
Europe/London
1602284400.0
```

When we call the `timestamp`-function without an attached timezone, the system guesses it's local time. So while the actual datetime object is shown correctly, on hashing the timezone is applied again. I guess to get this right, the Berlin timezone should be used as a static timezone instead of just using local time for the hashing. Something like

```python
h.update(str(start.replace(tzinfo=ZoneInfo('Europe/Berlin').timestamp()).encode())
```

instead of https://github.com/fnep/mtv_dl/blob/master/mtv_dl.py#L469 to get this always right.

```
root@artemis:~# cat /etc/timezone && python3 -c "import datetime; print(datetime.datetime(2020,10,10).timestamp());"
Europe/Berlin
1602280800.0
root@artemis:~# cat /etc/timezone && python3 -c "import datetime; from zoneinfo import ZoneInfo; print(datetime.datetime(2020,10,10).replace(tzinfo=ZoneInfo('Europe/Berlin')).timestamp());"
Europe/Berlin
1602280800.0
root@vidserv:~# cat /etc/timezone && python3 -c "import datetime; from zoneinfo import ZoneInfo; print(datetime.datetime(2020,10,10).replace(tzinfo=ZoneInfo('Europe/Berlin')).timestamp());"
Europe/London
1602280800.0
```

This issue would also arise if you go out of the country, change the TZ of you laptop and connect to home via VPN. Then `mtv_dl` would also redownload existing media.

**Comment by maweki** [comment]
Should I create a PR? Is that something we would fix? Ideally, the hashes should always be the same on every system.

**Comment by fnep** [comment]
Sorry, ive missed your message 9 days ago somehow. I apologize.

A pull request would be very nice :)

**Comment by fnep** [comment]
Closing after no feedback for more than a month. Feel free to open it again.
