### ISSUE TITLE
Same Show on different channels redownloaded

### ISSUE THREAD

**Issue by strowi** [fnep/mtv_dl#56]
Hi,

first of all thanks for the work put into this. I recently moved mtv to my pi4 and it works really nice.;)

Not sure if this is inteded behaviour. But taking the 'famous' 'Tatort' as an example:

The show is being aired on multiple channels. At different times they show different (or same) episodes. 
If i set a filter `title!='Audiodeskription' title!='klare Sprache' title!='Trailer' topic='Tatort' duration+70m` i see a lot of duplicates with different hashes because of the channel-hash (even the start-time is identical).

Is this inteded? Are there shows with identical topic,title,size and time but different content?
Or could the channel-hash be removed to prevent redownloading? 
Or is there another possibility?

regards,
strowi

**Comment by fnep** [comment]
Hi,

have you tried adding `channel=ARD`? 

The hash is mostly to avoid downloading the exact same thing again and not "smart" in any way

**Comment by strowi** [comment]
yes. Sorry, should've mentioned.. some shows (probably older ones) are only shown on other channels than ARD. (and starting fresh I saw a lot of duplicates that would end up in the 10s of GB) 
Anyhow, I removed the channel from the hash on my local pi, so 'problem' solved for now. 😉
