### ISSUE TITLE
Example for download

### ISSUE THREAD

**Issue by dataAddictGit** [fnep/mtv_dl#58]
Hallo fnep,
vielen Dank für dieses tolle Paket. Sicherlich ist das kein Issue, sondern eher ein Bedienfehler. 
Ich habe meine Probleme etwas zu downloaden. 
Dazu nutze ich die folgende Zeile mit dem Ziel die Videos in den aktuellen Pfad zu kopieren. Ich hatte auch schon eine absolute Pfadangabe nach dem Muster 'E:\Videos\' probiert. Aber mit derselben Fehlermeldung.
mtv_dl.exe download topic='Elefant, Tiger' channel='MDR' -h --target='./{title}'

Daraufhin bekomme ich dann die folgenden Fehlermeldung 
![image](https://user-images.githubusercontent.com/82867950/204160238-c9ba6391-1821-4437-bfa6-58c085e7232d.png)

Ich würde mich freuen, wenn du mir auf die Sprünge helfen kannst.

Vielen Dank und Grüße,
Marcus

**Comment by fnep** [comment]
Hallo Marcus,

ich bin etwas ratlos, tippe aber es liegt daran, dass das Script versucht eine Datei mit Doppelpunkt im Namen anzulegen. Kannst du es mal mit `--no-subtitles` probieren?

Viele Grüße

Frank

**Comment by dataAddictGit** [comment]
Hallo Frank,
vielen Dank für die schnelle Hilfe. Ich habe es gerade mit der Option probiert. Damit konnte ich 5 Videos erfolgreich downloaden.

Vielen Dank und Viele Grüße
Marcus
