### ISSUE TITLE
Support for TV series

### ISSUE THREAD

**Issue by ChristianKuehnel** [fnep/mtv_dl#60]
First off: An amazing tool you have build there, @fnep ! I'm using it daily (well, my cron scheduler is 😉).

I've noticed that some TV series e.g. from ZDF are now using `(S01E01)` like episode markers in the `title` field. So we now have some data that we could use to guess TV series and slightly change the behavior of `mtv_dl`. It would be awesome if `mtv_dl` would use that information so that the Series appears nicely in the media centers (Emby, Kodi, Jellyfin, ...).

What I had in mind was:
* add a switch `--series` for the `download` command to enable special treatment of TV series. 
  * If that flag is set, do a few things differently, details below
  * In the beginning I would propose to let the user enable the series mode, maybe later automatically trigger it based on some heuristics.
* Extract the series/episode from the `title`, using a regex `\(S(\d+)/E(\d+)\)` for the first case:
  * (S01/E01), sample query: `mtv_dl -r23 dump topic="Nachtschicht" title=S01`
  * (123), sample query: `mtv_dl -r23 dump topic="Leopard, Seebär"`, here always assume `season=1`
* in the NFO file, 
  * use`<episodedetails>` instead of `<movie>`
  * add the additional details with`<season>XXX</season><episode>XXX</episode>`
* optional: change default name pattern (or let the user do that):
  * write all files into the same folder called `<topic>`
  * use naming schema for file names: `<topic> - SxxExx - <title>.<extension>` 
* optional: support episode and season also in the filters
* optional: create a root `NFO` file containing some general series information (not sure where to get the details from)

I didn't check if that series metadata would also be available somewhere in the database so that we don't need to guess it from the title...

If you're interested in such a feature, I could take a look in a couple of weeks and propose a pull request...

**Comment by fnep** [comment]
Hi, thank you for the idea! I really like it. Happy to see a pull request for it.  😊

**Comment by fnep** [comment]
This is now published as v0.23.0 on pypi.
