### ISSUE TITLE
DeprecationWarning: ijson works by reading bytes...

### ISSUE THREAD

**Issue by ChristianKuehnel** [fnep/mtv_dl#63]
When using `pytest` to test #61 I get this warning:

```
.venv/lib/python3.9/site-packages/ijson/compat.py:48
  /home/kuehnelc/git/mtv_dl/.venv/lib/python3.9/site-packages/ijson/compat.py:48: DeprecationWarning: 
  ijson works by reading bytes, but a string reader has been given instead. This
  probably, but not necessarily, means a file-like object has been opened in text
  mode ('t') rather than binary mode ('b').
  
  An automatic conversion is being performed on the fly to continue, but on the
  other hand this creates unnecessary encoding/decoding operations that decrease
  the efficiency of the system. In the future this automatic conversion will be
  removed, and users will receive errors instead of this warning. To avoid this
  problem make sure file-like objects are opened in binary mode instead of text
  mode.
  
    warnings.warn(_str_vs_bytes_warning, DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by fnep** [comment]
Thank so reporting. I will take a look on it as soon as I work next time on this project.

**Comment by fnep** [comment]
Not sure what exactly it is, but i was unable to get this warning with Python 3.10 in master (with a similar pytest.ini). Maybe you can give me some more details?

**Comment by Dobatymo** [comment]
The FAQ https://github.com/ICRAR/ijson#faq suggests to use byte streams. So this line https://github.com/fnep/mtv_dl/blob/7203f902047c50f861eb988e84c38fd230f0200b/mtv_dl.py#L512 should probably be changed to `with lzma.open(showlist_archive, 'rb') as fh:`

**Comment by fnep** [comment]
I also found this recommendation … i just wonder why i do not see the warning.

My hope was i can reproduce this myself, to see if it really was fixed with the change.

**Comment by ChristianKuehnel** [comment]
> Not sure what exactly it is, but i was unable to get this warning with Python 3.10 in master (with a similar pytest.ini). Maybe you can give me some more details?

Not really I was just using Python 3.9 that ships with Debian 11 and that warning appeared...

**Comment by fnep** [comment]
Ok, I've spent a few hours to reproduce this now, but without success. Anyhow, I see the file should be opened as binary, and so I changed it, hoping the warning hoes away for you.
