### ISSUE TITLE
sqlite3.OperationalError table main.show has 16 columns but 18 values were supplied

### ISSUE THREAD

**Issue by divialth** [fnep/mtv_dl#68]
Hi,

i had not run the tool for a while, and now fetched the ˋlatestˋ container image.  

After start the program crashes with this error:

```
2023-06-10T12:32:29+0000 CRITICAL <class 'sqlite3.OperationalError'>: table main.show has 16 columns but 18 values were supplied
  File "<string>", line 1, in <module>
  File "/mtv_dl.py", line 1462, in main
    showlist.initialize_if_old(refresh_after=int(arguments["--refresh-after"]))
  File "/mtv_dl.py", line 618, in initialize_if_old
    self.initialize_filmliste()
  File "/mtv_dl.py", line 380, in initialize_filmliste
    cursor.executemany(
```

I also tried the ˋmasterˋ image version. Same error was reported. 
It looks like the new columns are missing:

```
# sqlite3 .Filmliste.0.0.0.sqlite 
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> .schema main.show
CREATE TABLE show (
                    hash TEXT,
                    channel TEXT,
                    description TEXT,
                    region TEXT,
                    size INTEGER,
                    title TEXT,
                    topic TEXT,
                    website TEXT,
                    new BOOLEAN,
                    url_http TEXT,
                    url_http_hd TEXT,
                    url_http_small TEXT,
                    url_subtitles TEXT,
                    start TIMESTAMP,
                    duration TIMEDELTA,
                    age TIMEDELTA
                );
```

**Comment by fnep** [comment]
Thank you for this report. It looks like the docker image does not set the version number correctly what is normally part of the Filmliste filename. 

Please delete the `.Filmliste.0.0.0.sqlite` in your download directory and try again.

**Comment by divialth** [comment]
> Please delete the `.Filmliste.0.0.0.sqlite` in your download directory and try again.

After that it is working again. 
do you plan to fix the issue with the container image? If not a note in the readme would be perhaps a good idea.

**Comment by fnep** [comment]
My plan is to fix the image, yes. But I do not know yet what the best way for this is and also have no time at the moment to work on it (I took me a note for next week).

I could also try to detect if loading failed and remove the file, so it would at least work the second time, but it feels wrong.

**Comment by fnep** [comment]
Took me a while to figure out i just did not install poetry-dynamic-versioning in the Dockerfile 😂
