### ISSUE TITLE
Download progress output causes scrolling

### ISSUE THREAD

**Issue by Dobatymo** [fnep/mtv_dl#8]
`tqdm` automatically adjusts the size of the progressbar to match the terminal width. However if the description `desc` is too long (which it commonly is), it will overflow the line and cause the terminal to scroll.

```
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
Downloading 'NEO MAGAZIN ROYALE - History I - DAS steckt wirklich dahinter!' [ZDF, 'NEO MAGAZIN ROYALE', 2020-02-28 05:1
5:00+08:00, 8d45aebd]:   4%| | 32.2M/854M [02:10<53:39, 255kB/s]
```

It would be great if the description could be limited automatically, so that the progress output matches the terminal width.

**Comment by fnep** [comment]
I could reproduce the issue. Then i checked the [tqdm issue tracker](https://github.com/tqdm/tqdm/issues/690) and found they did some changes in v4.41. Could you please check you have the latest version?

``` shell
python3 -m pip install -U tqdm
```
For me this solves the ghosting, but looks not super nice because the whole row is cut instead of only the description.

Maybe we should really trim the description after so many characters and have a config for it. Just want to make sure I understand the problem.

**Comment by fnep** [comment]
Also, see the option I have added as a proposal (fd9a3fab) to limit the width. This could also be used in the config file but still is not applied to the description but to the whole bar (more in case the width detection fails).

**Comment by Dobatymo** [comment]
Yes, I was using an older version of tqdm (4.30). Updating "fixes" the problem the way you described. It still prints the same line 3 times for some reason, but not more often. I can live with that. But yes, the actual progress is cut off, which is not an ideal solution.

For me a command line option to limit the size of the description would be enough.

Automatic detection of the optimal description size would be best, but probably better implemented in tqdm itself and not here.

**Comment by fnep** [comment]
I see.

I have added an option to limit the description size in the `progress_bar_width` branch now. Either use `--description-width=30` or simply put `description-width: 5` in your `$HOME/.mtv_dl.yml` (hope this works under Windows 🤔).

If you confirm this to be fine for your case, i put it in master.

**Comment by Dobatymo** [comment]
Works perfectly, thanks. Both the option and the config file. `Path('~/.mtv_dl.yml').expanduser()` works as expected on Windows.

The use of f-strings increases the required python version from 3.5 to 3.6 I think. Or was 3.6 required before too? I don't mind, but maybe it's worth putting that into the readme.

Anyway, thanks for your quick response.

EDIT: Sorry, I just saw that the readme already specifies Python 3.6 ...

**Comment by fnep** [comment]
Perfect. So this is in master now.
