### ISSUE TITLE
What about a docker Container for it ?

### ISSUE THREAD

**Issue by xsasx** [fnep/mtv_dl#9]
Hi !

thank you very much for this great peace of software. Did you ever think about to make a docker container for this ?!

**Comment by fnep** [comment]
Not really, … but it makes sense and should be fairly easy. I will put it on my long term TODO list.

**Comment by xsasx** [comment]
thanks ;) and best regards also from germany  !

**Comment by fnep** [comment]
I just wrote and pushed a little Docker file (c3a1d33). Please give this a try. If it's working well for you, i will add a little section to the readme about it.

    docker run -t -v ~/Downloads/:/data/ efenka/mtv_dl list

*(Of course you need to modify the command to match your downloads directory.)*

**Comment by xsasx** [comment]
work with dockercompose 

looksgood 

version: '3.3'
services:
    mtv_dl:
        volumes:
            - '~/Downloads/:/data/'
        image: efenka/mtv_dl


sepearte config folder would be nice - with sample configs 

so seperate config and downloads

**Comment by fnep** [comment]
If you already have a config file, could you not simply mount it into the container? Source of this file can be wherever you want.

``` docker-compose
version: '3.3'
  services:
    mtv_dl:
      image: efenka/mtv_dl
      volumes:
        - '~/Downloads/:/data/'
        - '~/.mtv_dl.yml:/root/.mtv_dl.yml'
```

**Comment by fnep** [comment]
@xsasx Did the config file solution work for you?
