### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jtrees** [fnep/mtv_dl#91]
Thank you for this great piece of software.

I'm trying to package it for nixpkgs ([PR](https://github.com/NixOS/nixpkgs/pull/270215)) but the out-of-date dependencies for `0.23.12` are causing issues. Any chance you could tag a new release with newer deps?

EDIT: I noticed that an update of `iso8601` to `2.x.x` would also be helpful and created a PR (#92) for it.

**Comment by fnep** [comment]
Thank you for your work. I will take a look later this week and publish a new version.

**Comment by fnep** [comment]
I just uploaded version 0.23.25 to https://pypi.org/project/mtv-dl/. Hope this works for you.

**Comment by jtrees** [comment]
Thanks! This looks good. I'm fixing up the nixpkgs PR now.
